# Generated by Django 4.1.4 on 2022-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='first_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examiner',
            name='last_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
