# Generated by Django 4.1.4 on 2022-12-17 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 17, 10, 18, 54, 37133, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.TimeField(),
        ),
    ]
