# Generated by Django 4.1.4 on 2022-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_test_created_alter_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
